#!/usr/bin/env python3
"""AutoSurvey가 만든 .md를 Overleaf에 바로 올릴 수 있는 .tex로 변환한다.

pandoc만으로는 안 되는 이유가 세 가지 있다.

1. 제목 중복 — 파이프라인이 아웃라인 제목을 먼저 쓰고, 모델이 본문 첫 줄에
   자기 제목을 또 쓴다. 번호가 같은 헤딩이 연달아 나오면 앞의 것만 남긴다.
2. 헤딩 레벨 불일치 — 모델이 서브섹션을 '## 2.5'로 쓸 때가 있다.
   번호의 점 개수로 레벨을 다시 매긴다.
3. 인용이 평문 — '[1; 2]'가 그냥 글자라 클릭이 안 된다. thebibliography와
   \\cite로 바꿔야 Overleaf에서 인용을 눌러 참고문헌으로 점프할 수 있다.

사용법:
    python scripts/md_to_tex.py "output/deepseek-v4-pro/In-context Learning.md"
"""

import argparse
import os
import re
import subprocess
import sys

HEADING_RE = re.compile(r'^(#{1,6})\s+(.*?)\s*$')
# '1.2.3 제목' 형태에서 번호를 떼어낸다.
NUMBER_RE = re.compile(r'^(\d+(?:\.\d+)*)\.?\s+(.*)$')
# 참고문헌 한 줄: '[12] Title'
REF_RE = re.compile(r'^\[(\d+)\]\s*(.*)$')
# 본문 인용: '[1]', '[1; 2]', '[1; 2; 3]'
# ⚠ pandoc의 LaTeX 라이터는 대괄호를 '{[}...{]}' 로 이스케이프한다
# (선택인자와 헷갈리지 않게 하려고). 변환 후 텍스트에 적용하므로 두 형태를 다 받는다.
CITE_RE = re.compile(r'(?:\{\[\}|\[)(\d+(?:\s*;\s*\d+)*)(?:\{\]\}|\])')

PREAMBLE = r"""\documentclass[11pt]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{longtable,booktabs}
\usepackage{microtype}
% hyperref goes last; it makes \cite clickable through to the bibliography.
\usepackage[colorlinks=true,linkcolor=blue,citecolor=teal,urlcolor=magenta]{hyperref}

% pandoc emits \tightlist but expects the preamble to define it.
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% If the compile times out on Overleaf, comment out \tableofcontents below first.
\title{@@TITLE@@}
\author{Generated by AutoSurvey}
\date{}

\begin{document}
\maketitle
\tableofcontents
\newpage

"""


# pdflatex + inputenc(utf8)이 처리하지 못하는 문자들. 그냥 두면 Overleaf 기본
# 컴파일러에서 "Unicode character not set up for use with LaTeX" 에러가 난다.
# —, –, ’, “, ×, é 같은 나머지 비ASCII는 pandoc이 알아서 처리하므로 건드리지 않는다.
UNICODE_FIXES = {
    '‑': '-',              # NON-BREAKING HYPHEN (출력물 전체에 844곳)
    '→': r'$\rightarrow$',
    'π': r'$\pi$',
    '₂': r'$_2$',
    '\U0001d458': '$k$',        # MATHEMATICAL ITALIC SMALL K
}


def sanitize_unicode(text):
    """pdflatex이 못 먹는 문자를 치환한다. (치환된 텍스트, 총 치환 횟수)"""
    total = 0
    for bad, good in UNICODE_FIXES.items():
        n = text.count(bad)
        if n:
            text = text.replace(bad, good)
            total += n
    return text, total


def normalize_math(text):
    r"""\( \) / \[ \] 를 $ $$ 로 바꾼다.

    pandoc의 markdown 리더는 tex_math_single_backslash 확장이 없으면
    \( 를 수식으로 보지 않고 백슬래시를 그대로 출력해버린다.
    """
    text = re.sub(r'\\\((.+?)\\\)', r'$\1$', text, flags=re.DOTALL)
    text = re.sub(r'\\\[(.+?)\\\]', r'$$\1$$', text, flags=re.DOTALL)
    return text


def split_references(lines):
    """본문과 참고문헌을 나눈다. (본문 lines, {번호: 제목})"""
    for i, line in enumerate(lines):
        if re.match(r'^#{1,3}\s+References\s*$', line.strip()):
            body, ref_lines = lines[:i], lines[i + 1:]
            break
    else:
        return lines, {}

    refs = {}
    for line in ref_lines:
        m = REF_RE.match(line.strip())
        if m:
            refs[int(m.group(1))] = m.group(2).strip()
    return body, refs


def clean_headings(lines):
    """중복 제목을 지우고, 번호 깊이에 맞춰 레벨을 다시 매긴다.

    번호가 같은 헤딩이 (빈 줄만 사이에 두고) 연달아 나오면 앞의 것만 남긴다.
    앞의 것이 아웃라인에서 온 정식 제목이기 때문이다.
    """
    out = []
    pending = None       # (원본 인덱스 in out, 번호)
    dropped = 0

    for line in lines:
        m = HEADING_RE.match(line)
        if not m:
            if line.strip():
                pending = None   # 본문이 끼어들면 연속이 끊긴다
            out.append(line)
            continue

        body = m.group(2).strip()
        num_m = NUMBER_RE.match(body)

        if num_m:
            number, title = num_m.group(1), num_m.group(2)
            # 문서 제목(#)은 이미 본문에서 빼내 \title로 보냈으므로 한 단계씩 올린다.
            # '1' -> #(\section), '1.1' -> ##(\subsection), '1.1.1' -> ###(\subsubsection)
            level = min(number.count('.') + 1, 6)
        else:
            number, title, level = None, body, len(m.group(1))

        if number and pending == number:
            dropped += 1          # 직전과 같은 번호 → 버린다
            continue

        pending = number
        # 번호는 떼어낸다. LaTeX가 알아서 붙이므로 두면 '1 1 Introduction'이 된다.
        out.append('#' * level + ' ' + title)

    return out, dropped


def to_cite(match, refs):
    nums = [int(n) for n in re.split(r'\s*;\s*', match.group(1))]
    if not all(n in refs for n in nums):
        return match.group(0)     # 참고문헌에 없는 번호면 원문 그대로 둔다
    return '\\cite{' + ','.join(f'ref{n}' for n in nums) + '}'


def tex_escape(text):
    """참고문헌 제목처럼 pandoc을 안 거치는 평문을 LaTeX에 안전하게 넣는다."""
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'),
                 ('$', r'\$'), ('#', r'\#'), ('_', r'\_'), ('{', r'\{'),
                 ('}', r'\}'), ('~', r'\textasciitilde{}'),
                 ('^', r'\textasciicircum{}')]:
        text = text.replace(a, b)
    return text


def build_bibliography(refs):
    if not refs:
        return ''
    width = str(max(refs))
    out = ['\\begin{thebibliography}{' + width + '}',
           '\\addcontentsline{toc}{section}{References}']
    for n in sorted(refs):
        # 이스케이프를 먼저 하고 유니코드를 고친다. 순서를 뒤집으면 치환으로 넣은
        # $\rightarrow$ 의 백슬래시와 $ 가 다시 이스케이프돼 글자로 찍힌다.
        title, _ = sanitize_unicode(tex_escape(refs[n]))
        out.append('\\bibitem{ref%d} %s' % (n, title))
    out.append('\\end{thebibliography}')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('md_path')
    ap.add_argument('-o', '--output', help='기본값: 같은 경로의 .tex')
    ap.add_argument('--keep-plain-citations', action='store_true',
                    help='[1; 2]를 \\cite로 바꾸지 않고 평문으로 둔다')
    args = ap.parse_args()

    with open(args.md_path, encoding='utf-8') as f:
        raw = f.read()

    lines = raw.split('\n')
    body_lines, refs = split_references(lines)

    # 문서 제목은 첫 '# ' 헤딩에서 가져오고 본문에서는 뺀다 (\maketitle이 찍는다).
    title = os.path.splitext(os.path.basename(args.md_path))[0]
    for i, line in enumerate(body_lines):
        m = HEADING_RE.match(line)
        if m and len(m.group(1)) == 1:
            title = m.group(2).strip()
            body_lines = body_lines[:i] + body_lines[i + 1:]
            break

    body_lines, dropped = clean_headings(body_lines)
    body_md, fixed_chars = sanitize_unicode(normalize_math('\n'.join(body_lines)))

    proc = subprocess.run(
        ['pandoc', '-f', 'markdown+tex_math_dollars-auto_identifiers',
         '-t', 'latex', '--wrap=preserve'],
        input=body_md, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit('pandoc 실패:\n' + proc.stderr)
    body_tex = proc.stdout

    cite_count = 0
    if not args.keep_plain_citations:
        body_tex, cite_count = CITE_RE.subn(lambda m: to_cite(m, refs), body_tex)

    out_path = args.output or os.path.splitext(args.md_path)[0] + '.tex'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(PREAMBLE.replace('@@TITLE@@', tex_escape(title)))
        f.write(body_tex)
        f.write('\n\n')
        f.write(build_bibliography(refs))
        f.write('\n\n\\end{document}\n')

    print(f'생성: {out_path}')
    print(f'  제목: {title}')
    print(f'  중복 헤딩 제거: {dropped}개')
    print(f'  pdflatex 미지원 문자 치환: {fixed_chars}곳')
    print(f'  참고문헌: {len(refs)}개')
    print(f'  \\cite 변환: {cite_count}곳')
    leftover = len(CITE_RE.findall(body_tex))
    if leftover:
        print(f'  ⚠ 참고문헌에 없는 인용 번호 {leftover}곳은 평문으로 남겼습니다')


if __name__ == '__main__':
    main()
