#!/usr/bin/env python3
"""AutoSurvey가 만든 .md를 Overleaf에 바로 올릴 수 있는 .tex로 변환한다.

pandoc만으로는 안 되는 이유가 세 가지 있다.

1. 제목 중복 — 파이프라인이 아웃라인 제목을 먼저 쓰고, 모델이 본문 첫 줄에
   자기 제목을 또 쓴다. 번호가 같은 헤딩이 연달아 나오면 앞의 것만 남긴다.
2. 헤딩 레벨 불일치 — 모델이 서브섹션을 '## 2.5'로 쓸 때가 있다.
   번호의 점 개수로 레벨을 다시 매긴다.
3. 인용이 평문 — '[1; 2]'가 그냥 글자라 클릭이 안 된다. thebibliography와
   \\cite로 바꿔야 Overleaf에서 인용을 눌러 참고문헌으로 점프할 수 있다.

사용법:
    python scripts/md_to_tex.py "output/deepseek-v4-pro/In-context Learning.md"
"""

import argparse
import json
import os
import re
import subprocess
import sys

# pandoc 리더 확장. 켜고 끄는 이유가 각각 있다.
#   +tex_math_dollars   $...$ 를 수식으로 읽는다 (normalize_math 가 \( 를 $ 로 바꾼다)
#   -auto_identifiers   헤딩마다 \hypertarget 을 붙이는 걸 막는다
#   -raw_tex            모델이 쓴 '\l' 같은 부스러기를 LaTeX 명령으로 통과시키지
#                       않는다. 통과하면 "Undefined control sequence" 로 죽는다.
#   -simple_tables      본문에 '---' 가 두 개 이상이면 그 사이를 통째로 표로
#   -multiline_tables   먹어버린다. 헤딩이 평문이 되고 \\ 가 섞여 나온다.
#   -yaml_metadata_block  위를 막으면 같은 '---' 가 이번엔 YAML 메타데이터로
#                       잡혀 파싱 에러로 죽는다. 셋을 같이 꺼야 한다.
#                       모델이 쓴 '---' 는 가로줄이지 구조가 아니다.
PANDOC_FORMAT = ('markdown+tex_math_dollars-auto_identifiers'
                 '-raw_tex-simple_tables-multiline_tables-yaml_metadata_block')

HEADING_RE = re.compile(r'^(#{1,6})\s+(.*?)\s*$')
# '1.2.3 제목' 형태에서 번호를 떼어낸다.
NUMBER_RE = re.compile(r'^(\d+(?:\.\d+)*)\.?\s+(.*)$')
# 참고문헌 한 줄: '[12] Title'
REF_RE = re.compile(r'^\[(\d+)\]\s*(.*)$')
# 본문 인용: '[1]', '[1; 2]', '[1; 2; 3]'
# ⚠ pandoc의 LaTeX 라이터는 대괄호를 '{[}...{]}' 로 이스케이프한다
# (선택인자와 헷갈리지 않게 하려고). 변환 후 텍스트에 적용하므로 두 형태를 다 받는다.
CITE_RE = re.compile(r'(?:\{\[\}|\[)(\d+(?:\s*;\s*\d+)*)(?:\{\]\}|\])')

PREAMBLE = r"""\documentclass[11pt]{article}

\usepackage[utf8]{inputenc}
% microtype 의 폰트 확장은 scalable 폰트를 요구한다. 기본 CM 이 비트맵(Type3)으로
% 잡히는 배포판에서는 lmodern 없이는 "auto expansion is only possible with
% scalable fonts" 로 컴파일이 죽는다.
\usepackage{lmodern}
\usepackage[T1]{fontenc}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{longtable,booktabs}
\usepackage{microtype}
% svgnames 를 줘야 teal 이 정의된다. 없으면 \cite 하나마다
% "Undefined color `teal'" 이 뜬다 (본편 산출물에서 732회).
\usepackage[svgnames]{xcolor}
% hyperref goes last; it makes \cite clickable through to the bibliography.
\usepackage[colorlinks=true,linkcolor=blue,citecolor=teal,urlcolor=magenta]{hyperref}

% pandoc emits \tightlist but expects the preamble to define it.
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

% If the compile times out on Overleaf, comment out \tableofcontents below first.
\title{@@TITLE@@}
\author{Generated by AutoSurvey}
\date{}

\begin{document}
\maketitle
\tableofcontents
\newpage

"""


# pdflatex + inputenc(utf8)이 처리하지 못하는 문자들. 그냥 두면 Overleaf 기본
# 컴파일러에서 "Unicode character not set up for use with LaTeX" 에러가 난다.
# —, –, ’, “, ×, é 같은 나머지 비ASCII는 pandoc이 알아서 처리하므로 건드리지 않는다.
UNICODE_FIXES = {
    '‑': '-',              # NON-BREAKING HYPHEN (출력물 전체에 844곳)
    '→': r'$\rightarrow$',
    '←': r'$\leftarrow$',
    '⇒': r'$\Rightarrow$',
    '≈': r'$\approx$',
    '≤': r'$\leq$',
    '≥': r'$\geq$',
    '≠': r'$\neq$',
    '∼': r'$\sim$',
    '∞': r'$\infty$',
    '∈': r'$\in$',
    '∀': r'$\forall$',
    '∃': r'$\exists$',
    '∑': r'$\sum$',
    '∏': r'$\prod$',
    '√': r'$\sqrt{}$',
    '⋅': r'$\cdot$',
    'ℓ': r'$\ell$',          # SCRIPT SMALL L — 3DGS 편의 L1/L2 표기에서 나왔다
    'ℝ': r'$\mathbb{R}$',
    'ℕ': r'$\mathbb{N}$',
    '∇': r'$\nabla$',
    '∂': r'$\partial$',
    '∫': r'$\int$',
    '≡': r'$\equiv$',
    '⊕': r'$\oplus$',
    '⊗': r'$\otimes$',
    '∪': r'$\cup$',
    '∩': r'$\cap$',
    '⊆': r'$\subseteq$',
    '∅': r'$\emptyset$',
    '∠': r'$\angle$',
    '∥': r'$\parallel$',
    '₀': r'$_0$', '₁': r'$_1$', '₂': r'$_2$', '₃': r'$_3$', '₄': r'$_4$',
    '⁰': r'$^0$', '¹': r'$^1$', '²': r'$^2$', '³': r'$^3$', '⁴': r'$^4$',
    '\U0001d458': '$k$',        # MATHEMATICAL ITALIC SMALL K
}

# 그리스 문자는 하나씩 겪을 때마다 추가하는 대신 통째로 넣는다. 본편 산출물이
# α 두 개 때문에 컴파일이 죽었는데, 다음엔 β 나 λ 로 같은 일이 반복된다.
# 코드포인트 산술로 만들지 않는다 — 그리스 블록에는 ς(final sigma)와 예약된
# 빈 자리가 끼어 있어서 오프셋이 σ 부터 어긋난다.
for _ch, _name in zip('αβγδεζηθικλμνξοπρστυφχψω',
                      ('alpha beta gamma delta epsilon zeta eta theta iota '
                       'kappa lambda mu nu xi omicron pi rho sigma tau '
                       'upsilon phi chi psi omega').split()):
    UNICODE_FIXES.setdefault(_ch, '$\\%s$' % _name)
# 대문자는 라틴과 모양이 같은 것(Α, Β, Ε…)에 LaTeX 명령이 없다. 있는 것만 넣는다.
for _ch, _name in zip('ΓΔΘΛΞΠΣΥΦΨΩ',
                      ('Gamma Delta Theta Lambda Xi Pi Sigma Upsilon '
                       'Phi Psi Omega').split()):
    UNICODE_FIXES.setdefault(_ch, '$\\%s$' % _name)
UNICODE_FIXES.setdefault('ς', r'$\varsigma$')

# pandoc 이 알아서 LaTeX 로 옮기는 문자들. 남은 비ASCII 경고에서 제외한다.
PANDOC_HANDLES = set('—–―‘’“”„…×÷°±·§¶†‡•‰′″€£¥¢©®™'
                     'àáâãäåæçèéêëìíîïñòóôõöøùúûüýÿšžœ'
                     'ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÑÒÓÔÕÖØÙÚÛÜÝŠŽŒß')


def unhandled_unicode(text):
    """치환도 안 되고 pandoc 도 못 옮기는 문자를 센다. {문자: 횟수}

    이게 비면 pdflatex 이 "Unicode character not set up" 으로 죽을 일이 없다.
    비어 있지 않으면 UNICODE_FIXES 에 추가해야 한다는 신호다.
    """
    left = {}
    for ch in text:
        if ord(ch) > 127 and ch not in UNICODE_FIXES and ch not in PANDOC_HANDLES:
            left[ch] = left.get(ch, 0) + 1
    return left


def sanitize_unicode(text):
    """pdflatex이 못 먹는 문자를 치환한다. (치환된 텍스트, 총 치환 횟수)"""
    total = 0
    for bad, good in UNICODE_FIXES.items():
        n = text.count(bad)
        if n:
            text = text.replace(bad, good)
            total += n
    return text, total


def normalize_math(text):
    r"""\( \) / \[ \] 를 $ $$ 로 바꾼다.

    pandoc의 markdown 리더는 tex_math_single_backslash 확장이 없으면
    \( 를 수식으로 보지 않고 백슬래시를 그대로 출력해버린다.
    """
    text = re.sub(r'\\\((.+?)\\\)', r'$\1$', text, flags=re.DOTALL)
    text = re.sub(r'\\\[(.+?)\\\]', r'$$\1$$', text, flags=re.DOTALL)
    return text


def split_references(lines):
    """본문과 참고문헌을 나눈다. (본문 lines, {번호: 제목})"""
    for i, line in enumerate(lines):
        if re.match(r'^#{1,3}\s+References\s*$', line.strip()):
            body, ref_lines = lines[:i], lines[i + 1:]
            break
    else:
        return lines, {}

    refs = {}
    for line in ref_lines:
        m = REF_RE.match(line.strip())
        if m:
            refs[int(m.group(1))] = m.group(2).strip()
    return body, refs


def clean_headings(lines):
    """중복 제목을 지우고, 번호 깊이에 맞춰 레벨을 다시 매긴다.

    번호가 같은 헤딩이 (빈 줄만 사이에 두고) 연달아 나오면 앞의 것만 남긴다.
    앞의 것이 아웃라인에서 온 정식 제목이기 때문이다.
    """
    out = []
    pending = None       # (원본 인덱스 in out, 번호)
    dropped = 0

    for line in lines:
        m = HEADING_RE.match(line)
        if not m:
            if line.strip():
                pending = None   # 본문이 끼어들면 연속이 끊긴다
            out.append(line)
            continue

        body = m.group(2).strip()
        num_m = NUMBER_RE.match(body)

        if num_m:
            number, title = num_m.group(1), num_m.group(2)
            # 문서 제목(#)은 이미 본문에서 빼내 \title로 보냈으므로 한 단계씩 올린다.
            # '1' -> #(\section), '1.1' -> ##(\subsection), '1.1.1' -> ###(\subsubsection)
            level = min(number.count('.') + 1, 6)
        else:
            number, title, level = None, body, len(m.group(1))

        if number and pending == number:
            dropped += 1          # 직전과 같은 번호 → 버린다
            continue

        pending = number
        # 번호는 떼어낸다. LaTeX가 알아서 붙이므로 두면 '1 1 Introduction'이 된다.
        out.append('#' * level + ' ' + title)

    return out, dropped


def to_cite(match, refs):
    nums = [int(n) for n in re.split(r'\s*;\s*', match.group(1))]
    if not all(n in refs for n in nums):
        return match.group(0)     # 참고문헌에 없는 번호면 원문 그대로 둔다
    return '\\cite{' + ','.join(f'ref{n}' for n in nums) + '}'


def tex_escape(text):
    """참고문헌 제목처럼 pandoc을 안 거치는 평문을 LaTeX에 안전하게 넣는다."""
    for a, b in [('\\', r'\textbackslash{}'), ('&', r'\&'), ('%', r'\%'),
                 ('$', r'\$'), ('#', r'\#'), ('_', r'\_'), ('{', r'\{'),
                 ('}', r'\}'), ('~', r'\textasciitilde{}'),
                 ('^', r'\textasciicircum{}')]:
        text = text.replace(a, b)
    return text


def load_detail(md_path):
    """옆에 있는 .json의 reference_detail을 읽는다. (없으면 빈 dict)

    scripts/enrich_references.py가 DB와 조인해 넣어준 서지정보다.
    .md에는 제목밖에 없어서 이게 없으면 arXiv ID도 링크도 못 넣는다.
    """
    jf = os.path.splitext(md_path)[0] + '.json'
    if not os.path.exists(jf):
        return {}
    with open(jf, encoding='utf-8') as f:
        return json.load(f).get('reference_detail') or {}


def format_bibitem(n, title, info):
    """제목 + arXiv ID + 연도 + 클릭 가능한 링크.

    저자와 게재지는 넣을 수 없다. DB(arxiv_paper_db.json)에 id/title/url/date만
    있고 저자 메타데이터가 없기 때문이다.
    """
    # 이스케이프를 먼저 하고 유니코드를 고친다. 순서를 뒤집으면 치환으로 넣은
    # $\rightarrow$ 의 백슬래시와 $ 가 다시 이스케이프돼 글자로 찍힌다.
    # arXiv 제목은 원본에 줄바꿈과 들여쓰기가 들어 있어 공백이 겹친다.
    text, _ = sanitize_unicode(tex_escape(re.sub(r'\s+', ' ', title).strip()))
    if not info:
        return '\\bibitem{ref%d} %s' % (n, text)

    parts = [text.rstrip('.') + '.']
    arxiv_id = info.get('id', '')
    year = (info.get('date') or '')[:4]
    if arxiv_id:
        parts.append('arXiv:%s%s.' % (tex_escape(arxiv_id),
                                      (', %s' % year) if year else ''))
    if info.get('url'):
        # \url은 hyperref가 제공한다. 내용에 특수문자가 없는 arXiv 링크라 안전하다.
        parts.append('\\url{%s}' % info['url'])
    return '\\bibitem{ref%d} %s' % (n, ' '.join(parts))


def build_bibliography(refs, detail):
    if not refs:
        return ''
    width = str(max(refs))
    out = ['\\begin{thebibliography}{' + width + '}',
           '\\addcontentsline{toc}{section}{References}']
    for n in sorted(refs):
        out.append(format_bibitem(n, refs[n], detail.get(str(n))))
    out.append('\\end{thebibliography}')
    return '\n'.join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('md_path')
    ap.add_argument('-o', '--output', help='기본값: 같은 경로의 .tex')
    ap.add_argument('--keep-plain-citations', action='store_true',
                    help='[1; 2]를 \\cite로 바꾸지 않고 평문으로 둔다')
    args = ap.parse_args()

    with open(args.md_path, encoding='utf-8') as f:
        raw = f.read()

    lines = raw.split('\n')
    body_lines, refs = split_references(lines)
    detail = load_detail(args.md_path)

    # 문서 제목은 첫 '# ' 헤딩에서 가져오고 본문에서는 뺀다 (\maketitle이 찍는다).
    title = os.path.splitext(os.path.basename(args.md_path))[0]
    for i, line in enumerate(body_lines):
        m = HEADING_RE.match(line)
        if m and len(m.group(1)) == 1:
            title = m.group(2).strip()
            body_lines = body_lines[:i] + body_lines[i + 1:]
            break

    body_lines, dropped = clean_headings(body_lines)
    body_md, fixed_chars = sanitize_unicode(normalize_math('\n'.join(body_lines)))

    proc = subprocess.run(
        ['pandoc', '-f', PANDOC_FORMAT,
         '-t', 'latex', '--wrap=preserve'],
        input=body_md, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit('pandoc 실패:\n' + proc.stderr)
    body_tex = proc.stdout

    cite_count = 0
    if not args.keep_plain_citations:
        body_tex, cite_count = CITE_RE.subn(lambda m: to_cite(m, refs), body_tex)

    out_path = args.output or os.path.splitext(args.md_path)[0] + '.tex'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(PREAMBLE.replace('@@TITLE@@', tex_escape(title)))
        f.write(body_tex)
        f.write('\n\n')
        f.write(build_bibliography(refs, detail))
        f.write('\n\n\\end{document}\n')

    print(f'생성: {out_path}')
    print(f'  제목: {title}')
    print(f'  중복 헤딩 제거: {dropped}개')
    print(f'  pdflatex 미지원 문자 치환: {fixed_chars}곳')
    left = unhandled_unicode(body_md)
    if left:
        # ⚠ 이름을 detail 로 쓰면 아래 참고문헌 집계의 detail(dict)을 덮어쓴다.
        left_desc = ', '.join('%s(U+%04X)×%d' % (c, ord(c), n)
                              for c, n in sorted(left.items(), key=lambda x: -x[1])[:8])
        print(f'  ⚠ 치환표에 없는 비ASCII {sum(left.values())}곳: {left_desc}')
        print(f'    pdflatex 에서 죽을 수 있습니다. UNICODE_FIXES 에 추가하세요.')
    linked = sum(1 for n in refs if detail.get(str(n), {}).get('id'))
    print(f'  참고문헌: {len(refs)}개 (arXiv ID/링크 {linked}개)')
    if refs and not linked:
        print('  ⚠ reference_detail이 없습니다. '
              'scripts/enrich_references.py 를 먼저 돌리면 arXiv ID와 링크가 들어갑니다')
    print(f'  \\cite 변환: {cite_count}곳')
    leftover = len(CITE_RE.findall(body_tex))
    if leftover:
        print(f'  ⚠ 참고문헌에 없는 인용 번호 {leftover}곳은 평문으로 남겼습니다')


if __name__ == '__main__':
    main()
